gantt
dateFormat  SS
axisFormat %S
title Direct Interface

section ID=0
8s               :  8s, 00, 8s
7s               :  7s, after 8s, 7s
6s               :  6s, after 7s, 6s
section ID=1
5s               :  5s, 00, 5s
4s               :  4s, after 5s, 4s
3s               :  3s, after 4s, 3s

section ID=2
2s               :  2s, 00, 2s
1s               :  1s, after 2s, 1s
