gantt
dateFormat  SS
axisFormat %S
title Task Interface

section ID=0
8s               :  8s, 00, 8s
3s               :  3s, after 8s, 3s
2s               :  2s, after 3s, 2s
section ID=1
7s               :  7s, 00, 7s
4s               :  4s, after 7s, 4s
1s               :  1s, after 5s, 1s

section ID=2
6s               :  6s, 00, 6s
5s               :  5s, after 6s, 5s