[package]
name = "euclidean_distance"
version = "0.1.0"
authors = ["Gerhard Bräunlich <g.braeunlich@disroot.org>"]
edition = "2018"


[lib]
name = "euclidean_distance"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.12"

[dependencies.pyo3]
version = "0.12"
features = ["extension-module"]
